### PR TITLE
MNT: Sort events so oldest is first

### PR DESCRIPTION
**Pull request by ericdill**
Fixes the problem where events are returned newest first. This causes issues in suitcase.

https://gist.github.com/ericdill/11c77848fee4725efdef2a9d4e2fc2c6

### CODE REVIEW

**Comment by ericdill** [comment]
Ok so my solution in NSLS-II/suitcase#8 was to just use metadatastore.get_events_generator. This can wait.

**Comment by tacaswell** [comment]
Did you mean to close this?

**Comment by ericdill** [comment]
Yes. @arkilic had some reservations about sorting the events differently in `get_events()` which is fine by me as I don't need to use `get_events()` to achieve my objectives for NSLS-II/suitcase#8.

**Comment by tacaswell** [comment]
We are using an identical sort on `get_events_generator`

**Comment by ericdill** [comment]
@tacaswell I really don't care what we do here. Do you want this reopened so you can merge it?

**Pull request closed without merging**
