### PR TITLE
MNT: Fix uid bug and add test coverage for it

### LINKED ISSUE #143: uid bug in Document __repr__
Reported by @danielballan 

Bummer:

```
first_event.descriptor.data_keys
AttributeError: 'Document' object has no attribute 'uid'
```

### PR DESCRIPTION
**Pull request by ericdill**
- Closes #143

### CODE REVIEW

**Comment by ericdill** [comment]
That damn octal literal...

**Comment by tacaswell** [comment]
Do you intend to put in an octal number?

**Comment by ericdill** [comment]
No,  I copy pasted the majority of the new test files code from #142,  including the unintended octal literal

**Comment by ericdill** [comment]
Rolled this into #142

**Pull request closed without merging**
