### PR TITLE
~~100%~~  ~~99%~~ 98% test coverage

### PR DESCRIPTION
**Pull request by ericdill**
at least locally, let's see what coveralls thinks

### CODE REVIEW

**Comment by tacaswell** [comment]
I am not a huge fan of `#pragma: no cover` in the code base.  I would much rather we fake up `__import__`  http://stackoverflow.com/a/2481588/380231 to fake the exceptions or just leave them untested.

**Comment by ericdill** [comment]
is it the actual statement "#pragma: no cover" that you don't like or the concept of adding a line comment to ignore coverage for that line that you don't like?

**Comment by ericdill** [comment]
If it is the "#pragma: no cover" that you don't like, we can actually use anything we want. Other options include:
- #LazyDevsDontTest
- #AbandonAllHopeYeWhoUseThisLine
- #NoCoverageHere!

or really any other line comment that you can think of, those were just the fun ones that came to mind

**Comment by ericdill** [comment]
Grrrr this is so frustrating!!

### Coverage on travis:

```
Name                                                   Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------
metadatastore                                              4      0   100%   
metadatastore.api                                          2      0   100%   
metadatastore.commands                                   333      5    98%   285-289, 926
metadatastore.conf                                        22      2    91%   51, 68
metadatastore.doc                                        105      3    97%   88-90, 128
metadatastore.examples                                     0      0   100%   
metadatastore.examples.sample_data                         0      0   100%   
metadatastore.examples.sample_data.common                 40      0   100%   
metadatastore.examples.sample_data.multisource_event      40      0   100%   
metadatastore.examples.sample_data.temperature_ramp       39      0   100%   
metadatastore.odm_templates                               40      0   100%   
metadatastore.utils                                        0      0   100%   
------------------------------------------------------------------------------------
TOTAL                                                    625     10    98%   
----------------------------------------------------------------------
Ran 95 tests in 1.380s
OK
```

### Coverage on my laptop

```
Name                                                   Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------
metadatastore                                              4      0   100%   
metadatastore.api                                          2      0   100%   
metadatastore.commands                                   333      1    99%   926
metadatastore.conf                                        22      1    95%   51
metadatastore.doc                                        105      0   100%   
metadatastore.examples                                     0      0   100%   
metadatastore.examples.sample_data                         0      0   100%   
metadatastore.examples.sample_data.common                 40      0   100%   
metadatastore.examples.sample_data.multisource_event      40      0   100%   
metadatastore.examples.sample_data.temperature_ramp       39      0   100%   
metadatastore.odm_templates                               40      0   100%   
metadatastore.utils                                        0      0   100%   
------------------------------------------------------------------------------------
TOTAL                                                    625      2    99%   
----------------------------------------------------------------------
Ran 95 tests in 0.880s

OK
```

**Comment by tacaswell** [comment]
the concept of comments flagging skipping coverage tests

**Comment by ericdill** [comment]
Well then, here's a fun gotcha... after `git clean -xfd`, my local machine now produces results that match travis

**Comment by ericdill** [comment]
@tacaswell This is as much work as I am willing to put in for now. I am bored of trying to get all the lines covered. If you've got no objections, could you merge this in its current state?

**Pull request merged**
