### PR TITLE
Remove unused boltons imports

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tacaswell** [comment]
we should sort out how to re-impelment a LRU on this.

**Comment by ghost** [comment]
@tacaswell we should either give [pylru ](https://pypi.python.org/pypi/pylru) or [joblib](https://pythonhosted.org/joblib/) a shot here. I think joblib would be excellent for filestore as caches numpy arrays like no other tool out there. Once we decide which library, I can add the caching layer.

**Comment by tacaswell** [comment]
also, awj which naturally caches dataframes ;)

**Comment by ghost** [comment]
Right, this feature is in awj. I think you can increase the performance with joblib. Let's discuss this in person. (also, we can make a decision on which lib to use)

**Pull request merged**
