### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by tacaswell**
On a clean database the demo works correctly.

### CODE REVIEW

**Comment by ghost** [comment]
Should we update the tests before merging?

**Comment by tacaswell** [comment]
Yes, I am working on them now

**Comment by tacaswell** [comment]
This is going to break the DB at SRX as the events were going in without uids and there is a bunch of synthetic data in there with old-style event_descriptors.

Unless Garth did a whole bunch of scans after @dchabot and I left, we should probably just drop that db and start fresh tomorrow morning.

**Comment by tacaswell** [comment]
@stuwilkins These changes mean that the data from commissioning round 1 will not be accessible to the current version of the tools without a legit database migration effort (probably a day-ish of work), is this a problem?

**Comment by stuwilkins** [comment]
No. We can nuke what we did.

S
On Feb 11, 2015, at 11:18 PM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:

@stuwilkinshttps://github.com/stuwilkins These changes mean that the data from commissioning round 1 will not be accessible to the current version of the tools without a legit database migration effort (probably a day-ish of work), is this a problem?

**Comment by stuwilkins** [comment]
One other thing which came up speaking to @ericdill, can we make sure that the mongo database is configured correctly. i.e. it can be started and stopped by the sys-v scripts! We found that at CSX this was not the case and when the database started it:

1) Only bound to localhost
2) Saved data in a different directory. 

I think we should ensure that the darabase is also writing to a good place on the system.

Thanks,
Stuart

**Comment by ericdill** [comment]
Have a look at NSLS-II/docs#5. I think that should be a good start for discussions @stuwilkins

**Pull request merged**
