### PR TITLE
Use the correct license

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by tacaswell** [comment]
wait, what?

Also, leave the year an `2014-` so we don't have to update these every year.

**Comment by ericdill** [comment]
I don't understand your "wait what?"

**Comment by tacaswell** [comment]
How did we end up with a different license to begin with?

**Comment by tacaswell** [comment]
The current license is the EPICS license: http://www.aps.anl.gov/epics/license/open.php 

:+1: on moving to a more well known license

**Comment by danielballan** [comment]
I'll let @arkilic do the honors.

**Comment by ghost** [comment]
Goodbye epics license

**Pull request merged**
