### PR TITLE
WIP: Added some changes agreed upon in the meeting last week

### PR DESCRIPTION
**Pull request by ghost**
Do not merge this yet. I still have a lot of work to do in order to ensure everything is working properly. Created the PR so that we all see and comment on the changes. Any objection is more than welcome!

### CODE REVIEW

**Comment by tacaswell** [comment]
net negative for new features!

**Comment by ghost** [comment]
Huh... You were in the meeting and as far as in remember everybody nodded to these changes. Could you guys designate one person to tell me what everybody decides on or give me something in writing? I don't mind changing code but this is getting a little out of hand.

**Comment by tacaswell** [comment]
"+93  −110  " quoth the graphic at the top.  You removed more lines then you added _and_ you added new features.

That was meant to be a positive comment which was apparently not clear.

**Comment by ghost** [comment]
Two points: 1- English isn't my strongest suit 2- I'm not used to getting complements from Tom

**Pull request merged**
