### PR TITLE
ENH: First pass at converting events -> object

### PR DESCRIPTION
**Pull request by ericdill**
Requested by Claudio and Vivek

### CODE REVIEW

**Comment by ghost** [comment]
I don't mind adding dependencies as long as there is a justification to it. Why would you like to use pandas in mds? I don't think data formatting tools belong in metadataStore itself. We can work on purpose specific utility tools that use metadataStore as a dependency.

**Comment by ericdill** [comment]
Basically the same thing that `as_object` does but do `as_dataframe` (dataframe is the data structure for pandas)

**Comment by ericdill** [comment]
Does `this` refer to the current `as_object` function or the vaporware `as_dataframe` function?

**Comment by ghost** [comment]
It applies to both. We should keep metadataStore itself as simple and refined as we can with simple apis returning python dictionaries. All the other formatting can be distributed to other libraries. This way, once v4 stuff is introduced and metadataStore becomes a service, we won't have to add all these different formatting tools to the service side.

**Pull request closed without merging**
